### PR TITLE
Take sign into account when rounding numbers in (-1, 1), fixes #136

### LINKED ISSUE #136: round method works incorrectly for zero decimal places
The `.round(round_digits)` method does not work for rounding to zero decimal places.

```rust
let unrounded = BigDecimal::from_str("-0.68")?;
println!("{}", unrounded.round(0));
// output is 1 -- incorrect
println!("{}", unrounded.with_scale_round(0, RoundingMode::HalfUp));
// output is -1 -- correct
```

I do recognize that the docs for `round` specify that it is used for rounding to round_digits _after_ the decimal point, but it seems confusing that a round method doesn't work for round_digits less than 1.

> Return number rounded to round_digits precision after the decimal point

Shouldn't `round` work the same as `with_scale_round` just using the default rounding mode?

### PR DESCRIPTION
**Pull request by danilopedraza**
I think this should be enough to fix the problem. Let me know if I should make a change.

### CODE REVIEW

**Comment by akubera** [comment]
I'm sorry I never commented on this.

`BigDecimal::round` was the old implementation before `Context` and `RoundingMode` were added. I think the better option here is to replace the implementation of `round` with a call to `BigDecimal::with_scale_round`, using the default rounding mode.

```rust
    pub fn round(&self, round_digits: i64) -> BigDecimal {
        self.with_scale_round(round_digits, Context::default().rounding_mode())
    }

```

Doing that correctly rounds these test cases:

```
            ("-1.5", 0, "-2"),
            ("-1.2", 0, "-1"),
            ("-0.68", 0, "-1"),
            ("-0.5", 0, "0"),
            ("-0.49", 0, "0"),
```

**Comment by akubera** [comment]
Your commit has highlighted something something to me:

```rust
BigDecimal::new(BigInt::from_biguint(sign, BigUint::one()), round_digits);
```

There should be an easier way to copy the sign of a value.

```rust
BigDecimal::from_copysign(1, sign).with_scale(round_digits);

/// Create bigdecimal from `value`, copying the given sign (if not zero) 
pub fn<T: Into<BigDecimal>> from_copysign(value: T, sign: Sign) -> Self {
    let BigDecimal { scale, int_val } = value.into();
    let ( orig_sign, uint_val ) = int_val.into_parts();
    // NoSign means value is zero, and should remain so
    let new_sign = if orig_sign == Sign::NoSign { orig_sign } else { sign };

    // result Big
    BigDecimal { scale, int_val: BigInt::from_biguint(new_sign, uint_val) }
}
```

Does that seem good?

**Comment by akubera** [comment]
or `from_value_copying_sign`? 

`from_copysign` sounds like it would be constructing from a "copysign" object.

`from_value_and_sign` might be best. We'll leave "copying" to mean taking the sign from another value, not a sign itself.


```rust
let a = x.with_sign(Plus);
let a = x.with_copied_sign(Plus);

fn with_sign(&self, sign: Sign) -> BigDecimal;

// maybe "change" as the mutation verb? "set_sign"?
fn change_sign(&mut self, sign: Sign);

// copies the sign of any signed object  (note u8/16/etc are NOT signed)
fn copy_sign<S: num_traits::Signed>(&mut self, signed: S);
```

Open for opinions on verbage. What did you look for first when you went to create a "±1" ?

**Comment by danilopedraza** [comment]
> `BigDecimal::round` was the old implementation before `Context` and `RoundingMode` were added. I think the better option here is to replace the implementation of `round` with a call to `BigDecimal::with_scale_round`, using the default rounding mode.

Haha, I suspected this. I can do this change.

> `from_copysign` sounds like it would be constructing from a "copysign" object.

Yeah, I thought that too. `from_value_and_sign` sounds like a good name to me. It may be a bit long, but in the end is a kinda long operation.

> Open for opinions on verbage. What did you look for first when you went to create a "±1" ?

I was aware of the `from_biguint` function from previous use of the `BigInt` library. I don't have better ideas than the ones you already showed. My favorite is `with_sign`, since looks nice for composition. `change_sign` is my second choice, since it would be convenient to avoid copying (is that really a concern?).

**Comment by akubera** [comment]
Sorry, I've been making changes, rebase onto new trunk and push and the ci will pass again

**Comment by danilopedraza** [comment]
Haha, that was a bit clumsy. I think it's fine now.

**Comment by akubera** [comment]
Alright, merged. Thanks

**Comment by akubera** [comment]
image

That's what I like to see.

**Pull request merged**
