### PR TITLE
Update num-traits and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by akubera** [comment]
I was keeping these low for some reason, I think compatiblities with [diesel's](https://github.com/diesel-rs) dependencies. I think it'll be ok to merge, now; thanks.

**Comment by Eijebong** [comment]
I think this isn't going to be a problem for diesel. We can just specify bigdecimal as a range ;)

**Comment by akubera** [comment]
Published! Sorry about the delay.

**Comment by Eijebong** [comment]
Thanks, no problem :)

**Pull request merged**
